title: Jekill training with the bot
author: Mart54
email: test@test.com
description: > # this means to ignore newlines until "baseurl:"
  Just a test for the course from git learning. Thanks for that!

# social links
twitter_username: your-twitter-handle
github_username:  https://github.com/Mart54

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
